# Provides metrics about the state of a NATS server
# This plugin does not support FreeBSD
# collect interval
interval = 30

[[instances]]
## The address of the monitoring endpoint of the NATS server
server = "http://10.0.1.249:8221"
labels = {department="net", envir="test", zone="cn", devType="kvm", instance="10.0.1.249:8221"}
## Set response_timeout (default 5 seconds)
#response_timeout = "5s"
## interval = global.interval * interval_times
#interval_times = 2

[[instances]]
server = "http://10.0.1.249:8222"
labels = {department="net", envir="test", zone="cn", devType="kvm", instance="10.0.1.249:8222"}

[[instances]]
server = "http://10.0.1.249:8223"
labels = {department="net", envir="test", zone="cn", devType="kvm", instance="10.0.1.249:8223"}

